import '../styles/global.css'
import React from 'react';

/**
 * Default next-js entry point.
 * Auto-generated by NextJS startup script.
 * Only change is removing server-side injected CSS to enable materialUI.
 * More info:
 * https://github.com/vercel/next-learn/blob/master/basics/api-routes-starter/pages/_app.js (Part of startup script)
 * https://itnext.io/next-js-with-material-ui-7a7f6485f671 (MaterialUI with NextJS)
 * https://nextjs.org/learn/basics/create-nextjs-app (Step by step create NextJS guide)
 * 
 * @param {object} Component - NextJS Component object
 * @param {object} pageProps - NextJS pageProps object
 * @returns - React component
 */
export default function App({ Component, pageProps }) {
  React.useEffect(() => {
    // Remove the server-side injected CSS.
    const jssStyles = document.querySelector('#jss-server-side');
    if (jssStyles) {
      jssStyles.parentElement.removeChild(jssStyles);
    }
  }, []);

  return <Component {...pageProps} />
}